### ISSUE TITLE
64-bit AUTOEXEC is wrong

### ISSUE THREAD

**Issue by palmer-dabbelt** [sifive/openocd#22]

**Comment by mwachs5** [comment]
Actually, this is fine. I misunderstood the code, the different values were byte-wise, not word-wise, so it's only ever doing a 32-bit autoexec read/write using DATA0 to autoexec on. It returns ERROR_FAIL if you try to use a size > 32 bits.

So it's fine as-is. We can revisit if we need to in the future.
